name: Build and Commit PDF

on:
  push:
    branches:
      - main   # or whatever branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # 3. Run your Makefile target
      - name: Build PDF
        run: make   # or make pdf / make my_target depending on your Makefile

      # 4. Commit and push generated PDF
      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CV.pdf
          git commit -m "Update generated CV [skip ci]" || echo "No changes to commit"
          git push
